spring:
  r2dbc:
    url: r2dbc:pool:mysql://127.0.0.1:3306/practice
    username: root
    password: root
  config:
    import: configserver:http://localhost:8086
logging:
  level:
    root: info
  splunk:
    url: http://20.11.22.159:8088
    token: 92c9b613-cec1-47ad-a4d8-bc33c0bc7dc3