eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
management:
  tracing:
    sampling:
      probability: 1.0
logging:
  level:
    root: info
  appender:
    refs: console, Splunk
  console:
    pattern: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%t] %c{1}:%L - %m %X{correlationId}%n"
  splunk:
    host: COUNTRY
    index: api
    type: raw
    source: Country Application
    sourcetree: log4j
    messageFormat: text
    disableCertificateValidation: true
    pattern: "{&quot;time&quot;:&quot;%d{ISO8601}&quot;,&quot;level&quot;:&quot;%p&quot;,&quot;thread&quot;:&quot;%t&quot;,&quot;logger&quot;:&quot;%c{1}&quot;,&quot;message&quot;:&quot;%enc{%m}&quot;,&quot;correlationId&quot;:&quot;%X{correlationId}&quot;,&quot;exception&quot;:&quot;%enc{%ex}&quot;}"
server:
  port: 8089
