spring:
  config:
    import: configserver:http://localhost:8086
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka

#management:
#  zipkin:
#    tracing:
#      endpoint: http://localhost:8080/api/v2/spans
#  tracing:
#    sampling:
#      probability: 1.0
logging:
  level:
    root: info
  appender:
    refs: console, Splunk
  console:
    pattern: "%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m %X{correlationId}%n"
  splunk:
    url: http://20.11.22.159:8088
    token: 92c9b613-cec1-47ad-a4d8-bc33c0bc7dc3
    host: SplunkDemo
    index: api
    type: raw
    source: Splunk Demo
    sourcetype: log4j
    messageFormat: text
    disableCertificateValidation: true
    pattern: "{&quot;time&quot;:&quot;%d{ISO8601}&quot;,&quot;level&quot;:&quot;%p&quot;,&quot;thread&quot;:&quot;%t&quot;,&quot;logger&quot;:&quot;%c{1}&quot;,&quot;message&quot;:&quot;%enc{%m}&quot;,&quot;correlationId&quot;:&quot;%X{correlationId}&quot;,&quot;exception&quot;:&quot;%enc{%ex}&quot;}"