eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka
management:
  zipkin:
    tracing:
      endpoint: http://localhost:8080/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
splunk:
  url: http://20.11.22.159:8088/services/collector
  token: 92c9b613-cec1-47ad-a4d8-bc33c0bc7dc3