spring:
  datasource:
    url: jdbc:mysql://20.5.197.2:3306/wheel_inspection_db
    username: sanpadaworkshop
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


